# 通知配置
notify:
  telegram:
    bot_token: "your_telegram_bot_token"
    chat_id: "your_chat_id"

# 2bulu 配置
2bulu:
  accounts:
    - name: "2bulu账号1"
      cookie: "authCode=xxx_auth_code; token=xxx_token"
      params:
        authCode: "xxx_auth_code"
        authType: "1"
        deviceName: "iPhone 16 Pro"
        p_appVersion: "7.8.9"
        p_productType: "0"
        p_terminalType: "3"
        p_userId: "xxx_user_id"
        sdkLevel: "18.1.1"
        userId: "xxx_user_id"
        psign: "xxx_psign"
      tasks:
        - name: "每日签到"
          taskId: 1
        - name: "注册超过3年"
          taskId: 2

# 金价获取配置
gold_price:
  accounts:
    - name: "水贝金价"
      cookie: "Abp.Localization.CultureName=zh-CN; "

# 蓝鲸世界配置
lanjing:
  accounts:
    - name: "蓝鲸世界账号1"
      token: "your_access_token"
      mall_id: "1547404683667185667"

# 壹方城配置
yifangcheng:
  accounts:
    - name: "壹方城账号1"
      token: "your_token"
      mall_id: "000001"

# xxx 配置
xxx:
  accounts:
    - name: "xxx账号1"
      cookie: "authCode=xxx_auth_code; token=xxx_token"
      params:
        authCode: "xxx_auth_code"
        authType: "1"
        deviceName: "iPhone 16 Pro"
        p_appVersion: "7.8.9"
        p_productType: "0"
        p_terminalType: "3"
        p_userId: "xxx_user_id"
        sdkLevel: "18.1.1"
        userId: "xxx_user_id"
        psign: "xxx_psign"
      tasks:
        - name: "xxx每日任务"
          taskId: 1
        - name: "xxx特殊任务"
          taskId: 2
